---
# tasks file for k8s
- name: Make the Swap inactive
  become: true
  command: swapoff -a

- name: Remove Swap entry from /etc/fstab.
  become: true
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: Installing Prerequisites for Kubernetes
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - vim
      - software-properties-common
    state: present

- name: Add Docker’s official GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: docker
    mode: 0600

- name: Install Docker Engine.
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable service docker, and enable persistently
  become: true
  service:
    name: docker
    enabled: yes

- name: Add Google official GPG key
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes Repository
  become: true
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes
    mode: 0600

- name: Installing Kubernetes Cluster Packages.
  become: true
  apt:
    name:
      - kubeadm
      - kubectl
      - kubelet
    state: present

- name: Enable service kubelet, and enable persistently
  become: true
  service:
    name: kubelet
    enabled: yes

- name: Reboot all the kubernetes nodes.
  become: true
  reboot:
